variables:
  REGISTRY_HOST: registry.kresto.pp.ua
  IMAGE: $REGISTRY_HOST/$CI_PROJECT_PATH
  PROJECT_NAME: sharetribe
  SERVICE_NAME: app

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_HOST
  script:
    - docker build --pull --build-arg RS_GIT_REMOTE_URL=git@gitlab.kresto.pp.ua:example/example1.git --build-arg RS_GIT_BRANCH=sharetribe --tag $IMAGE .
    - docker push $IMAGE

deploy_development:
  stage: deploy
  image: kre100/rancher-cli-tools
  script:
    - rancher-compose --project-name ${PROJECT_NAME} up -d --upgrade --force-upgrade --pull ${SERVICE_NAME}
  environment:
    name: development
    url: http://sharetribe.kresto.pp.ua/
  only:
    - sharetribe
#  when: manual
