version: '2'
services:
  app:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
  proxy:
    scale: 1
    start_on_create: true
  smtpd:
    scale: 1
    start_on_create: true
  memcache:
    scale: 1
    start_on_create: true
  worker:
    scale: 1
    start_on_create: true
  mysqld:
    scale: 1
    start_on_create: true
  adminer:
    scale: 1
    start_on_create: true
